"""Agent-lane JSON payload types and (de)serialization.

The JSON contract between the CLI and the Claude Code skill for subscription-tier
résumé rewriting. All models are Pydantic BaseModel with frozen=True for immutability
where possible.

CRITICAL INVARIANT: JudgeRequest and JudgeItem are JD-blind by construction —
they have NO jd_skills field. The judge sees only the bullet and candidate text.
"""

from __future__ import annotations

from pathlib import Path
from typing import TypeVar

from pydantic import BaseModel, ConfigDict


class BulletRef(BaseModel):
    """Reference to a single résumé bullet for rewrite candidates."""

    model_config = ConfigDict(frozen=True)

    bullet_id: str
    entry_id: str
    a_text: str


class RewriteRequest(BaseModel):
    """Request to generate candidate rewrites for résumé bullets.

    Sent to the agent lane: the CLI passes the job description skills (jd_skills)
    so the agent can tailor candidates. The judge (downstream) does NOT receive
    this field — it is strictly separated.
    """

    model_config = ConfigDict(frozen=True)

    request_id: str
    jd_skills: list[str]
    bullets: list[BulletRef]


class Candidate(BaseModel):
    """A single candidate rewrite for a bullet."""

    model_config = ConfigDict(frozen=True)

    bullet_id: str
    candidate: str


class CandidatesFile(BaseModel):
    """File contract: candidates generated by the agent lane."""

    model_config = ConfigDict(frozen=True)

    request_id: str
    candidates: list[Candidate]


class JudgeItem(BaseModel):
    """A single item for the judge: bullet + candidate.

    CRITICAL: No jd_skills field. The judge is JD-blind by construction.
    """

    model_config = ConfigDict(frozen=True)

    bullet_id: str
    a_text: str
    candidate: str


class JudgeRequest(BaseModel):
    """Request to judge candidate rewrites.

    CRITICAL: This is a JD-free contract. The judge sees only the original bullet
    (a_text) and the candidate rewrite, with no context about the job description
    or skills. This enforces blind evaluation.
    """

    model_config = ConfigDict(frozen=True)

    request_id: str
    items: list[JudgeItem]


class Verdict(BaseModel):
    """A single verdict from the judge."""

    model_config = ConfigDict(frozen=True)

    bullet_id: str
    raw_reply: str


class VerdictsFile(BaseModel):
    """File contract: verdicts from the judge."""

    model_config = ConfigDict(frozen=True)

    request_id: str
    verdicts: list[Verdict]


T = TypeVar("T", bound=BaseModel)


def dump_json(model: BaseModel, path: Path) -> None:
    """Serialize a Pydantic model to JSON with 2-space indentation."""
    path.write_text(model.model_dump_json(indent=2), encoding="utf-8")


def load_json(cls: type[T], path: Path) -> T:
    """Deserialize JSON from a file into a Pydantic model."""
    return cls.model_validate_json(path.read_text(encoding="utf-8"))
