"""The golden projection: `project_pool` over the synthetic bundle, byte-compared against a
committed artifact.

There is no snapshot harness in this repo (`grep -rn "addoption"` is zero hits) — the convention,
established by `tests/profile_bundle/test_profile_bundle_schema_export.py`, is byte equality
against a live generator. The golden is regenerated by calling the generator and writing its
output by hand, never by an `--update` flag.

`resume_document_bytes` (`serialize.py`) is that generator here: it is the one place `Resume` ->
bytes is decided, and `test_the_projected_document_loads_through_the_production_loader`
(`test_projection_pool.py`) already proves those bytes round-trip through `load_resume`. This file
adds the missing property: that the bytes are not just round-trippable but STABLE, byte for byte,
against a reviewed artifact.
"""

from __future__ import annotations

from datetime import date
from importlib import resources

from boardwatch.projection.pool import project_pool
from boardwatch.projection.serialize import resume_document_bytes
from tools.generalization import allowlists as al

AS_OF = date(2026, 8, 13)

GOLDEN_PATH = "src/boardwatch/projection/examples/projection.golden.txt"


def _golden_bytes() -> bytes:
    traversable = resources.files("boardwatch.projection.examples").joinpath(
        "projection.golden.txt"
    )
    with resources.as_file(traversable) as path:
        return path.read_bytes()


def test_the_projected_document_matches_the_golden(projection_env) -> None:  # noqa: F811
    """Byte equality against the committed artifact, following
    `test_the_committed_bytes_are_the_exact_rendering`'s own pattern: sorted keys or fixed
    ordering aside, the point is that the FULL text matches, not merely that a file exists."""
    pool = project_pool(
        projection_env.bundle_root,
        projection_env.declaration,
        config_dir=projection_env.config_dir,
        as_of=AS_OF,
    )
    produced = resume_document_bytes(pool.resume)
    assert produced == _golden_bytes()


def test_the_shell_is_part_of_the_projected_document(projection_env) -> None:  # noqa: F811
    """The shell is model-only and never rendered, but it IS part of identity — so a change to
    it must be visible rather than silent."""
    pool = project_pool(
        projection_env.bundle_root,
        projection_env.declaration,
        config_dir=projection_env.config_dir,
        as_of=AS_OF,
    )
    assert pool.resume.header, "the inert shell must be present, not empty"
    assert any("@" in line for line in pool.resume.header)


def test_the_golden_is_registered_as_synthetic_shipped_data() -> None:
    entry = al.SHIPPED_DATA.get(GOLDEN_PATH)
    assert entry is not None, f"{GOLDEN_PATH} needs a reviewed SHIPPED_DATA entry (R7)"
    assert entry.kind == "fixture"
    assert entry.provenance == "synthetic"
    assert entry.pin.startswith("sha256:")
