"""schema v1

Revision ID: 8df3b3809bba
Revises: 
Create Date: 2026-06-11 20:35:50.383178
"""
import sqlalchemy as sa
from alembic import op

revision = '8df3b3809bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_state'))
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('last_health', sa.Text(), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("last_health IN ('ok', 'empty', 'dead', 'error')", name=op.f('ck_companies_last_health_enum')),
    sa.CheckConstraint("source IN ('registry', 'user')", name=op.f('ck_companies_source_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('provider', 'slug', name=op.f('uq_companies_provider_slug'))
    )
    op.create_table('http_cache',
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('url', name=op.f('pk_http_cache'))
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('skills_json', sa.JSON(), nullable=True),
    sa.Column('taxonomy_version', sa.Text(), nullable=True),
    sa.Column('target_titles_json', sa.JSON(), nullable=True),
    sa.Column('exclude_titles_json', sa.JSON(), nullable=True),
    sa.Column('locations_json', sa.JSON(), nullable=True),
    sa.Column('remote_only', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_profile_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('boards_attempted', sa.Integer(), nullable=False),
    sa.Column('boards_complete', sa.Integer(), nullable=True),
    sa.Column('postings_seen', sa.Integer(), nullable=True),
    sa.Column('new_count', sa.Integer(), nullable=True),
    sa.Column('closed_count', sa.Integer(), nullable=True),
    sa.Column('reopened_count', sa.Integer(), nullable=True),
    sa.Column('errors_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_table('board_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('postings_listed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('complete', 'partial', 'failed', 'unchanged')", name=op.f('ck_board_scans_status_enum')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_board_scans_company_id_companies')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_board_scans_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board_scans'))
    )
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('provider_posting_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('locations_json', sa.JSON(), nullable=True),
    sa.Column('remote_policy', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_missing', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('salary_min', sa.Numeric(), nullable=True),
    sa.Column('salary_max', sa.Numeric(), nullable=True),
    sa.Column('salary_currency', sa.Text(), nullable=True),
    sa.Column('salary_period', sa.Text(), nullable=True),
    sa.CheckConstraint("remote_policy IN ('remote', 'hybrid', 'onsite', 'unknown')", name=op.f('ck_postings_remote_policy_enum')),
    sa.CheckConstraint("status IN ('open', 'closed')", name=op.f('ck_postings_status_enum')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_postings_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postings')),
    sa.UniqueConstraint('company_id', 'provider_posting_id', name=op.f('uq_postings_company_id_provider_posting_id'))
    )
    op.create_index('ix_postings_content_hash', 'postings', ['content_hash'], unique=False)
    op.create_index('ix_postings_status_posted_at', 'postings', ['status', 'posted_at'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('engine_version', sa.Text(), nullable=False),
    sa.Column('json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('taxonomy')", name=op.f('ck_extractions_kind_enum')),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], name=op.f('fk_extractions_posting_id_postings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extractions')),
    sa.UniqueConstraint('posting_id', 'content_hash', 'kind', 'engine_version', name=op.f('uq_extractions_posting_id_content_hash_kind_engine_version'))
    )
    op.create_table('posting_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('new', 'reopened', 'closed', 'revised')", name=op.f('ck_posting_events_kind_enum')),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], name=op.f('fk_posting_events_posting_id_postings')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_posting_events_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posting_events')),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posting_events')
    op.drop_table('extractions')
    op.drop_index('ix_postings_status_posted_at', table_name='postings')
    op.drop_index('ix_postings_content_hash', table_name='postings')
    op.drop_table('postings')
    op.drop_table('board_scans')
    op.drop_table('runs')
    op.drop_table('profile')
    op.drop_table('http_cache')
    op.drop_table('companies')
    op.drop_table('app_state')
    # ### end Alembic commands ###
